/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Negocio.DTOs.BoletoDTO;
import Negocio.DTOs.FuncionDTO;
import Negocio.DTOs.GeneradorTicketPDF;
import Negocio.DTOs.PeliculaDTO;
import Negocio.DTOs.SalaDTO;
import Negocio.Negocio.ClienteNegocio;
import excepciones.cinepolisException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author stae
 */
public class CompraBoleto extends javax.swing.JFrame {

    ClienteNegocio c;
    PeliculaDTO pelicula;
    String sucursal;
    
    /**
     * Creates new form CompraBoleto
     */
    public CompraBoleto(String s, PeliculaDTO pelicula, ClienteNegocio c) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setSize(690, 560);
        this.c=c;
        this.pelicula=pelicula;
        System.out.println(s);
        this.sucursal=s;
        
        for (int i = 1; i <= 10; i++) {
            comboBoxCantidadBoletos.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboBoxCantidadBoletos = new javax.swing.JComboBox<>();
        btnCompraBoletos = new javax.swing.JButton();
        informacionDeFuncion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Compra de Boletos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 330, 80));

        jPanel2.setBackground(new java.awt.Color(12, 33, 63));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("←");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnRegresar)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad de Boletos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 50));
        jPanel1.add(comboBoxCantidadBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 40));

        btnCompraBoletos.setBackground(new java.awt.Color(102, 204, 255));
        btnCompraBoletos.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        btnCompraBoletos.setForeground(new java.awt.Color(255, 255, 255));
        btnCompraBoletos.setText("Confirmar Compra");
        btnCompraBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraBoletosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompraBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, 40));

        javax.swing.GroupLayout informacionDeFuncionLayout = new javax.swing.GroupLayout(informacionDeFuncion);
        informacionDeFuncion.setLayout(informacionDeFuncionLayout);
        informacionDeFuncionLayout.setHorizontalGroup(
            informacionDeFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        informacionDeFuncionLayout.setVerticalGroup(
            informacionDeFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel1.add(informacionDeFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 270, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompraBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraBoletosActionPerformed
        int cantidadBoletos = (int) comboBoxCantidadBoletos.getSelectedItem();

        if (sucursal == null || pelicula.getId() == null) {
            System.out.println("Sucursal o ID de Película es nulo"+sucursal+" s "+ pelicula.getId()+" ");
            return;
        }

        if (cantidadBoletos != 0 ) {
            if (cantidadBoletos > 0) {
                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas comprar " + cantidadBoletos+" boletos para la película '" +" a "+cantidadBoletos*50 +" Para: " + pelicula.getTitulo() + "' en la sucursal '" + sucursal + "'?", "Confirmar Compra", JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    try {
                        JOptionPane.showMessageDialog(this, "¡Compra de " + cantidadBoletos + " boletos confirmada!", "Compra Confirmada", JOptionPane.INFORMATION_MESSAGE);
                        BoletoDTO boleto=new BoletoDTO();

                        boleto.setCosto(cantidadBoletos*50);
                        boleto.setEstado(true);
                        boleto.setFechaCompra(new Date());

                        boleto.setCliente(c.convertirAEntidad(c.obtenerClientePorID(c.getId())));
                        FuncionDTO f=c.obtenerIdFuncionPorSucursalYPelicula(sucursal, pelicula.getId());
                        boleto.setFuncion(c.convertirAEntidadED(f));

                        c.insertarBoleto(boleto);
                        SalaDTO sala=c.obtenerSalaFuncionSucursal(sucursal,f);
                        System.out.println(" "+sala.getNumero());
                        try {
                            GeneradorTicketPDF.generarTicketPDF(boleto, sucursal, pelicula, sala, cantidadBoletos);
                        } catch (IOException ex) {
                            System.out.println(ex.getMessage());
                        }
                        Cartelera ca=new Cartelera(sucursal,c);
                        ca.setVisible(true);
                        this.dispose();

                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    } catch (cinepolisException ex) {
                        System.out.println(ex.getMessage());
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Compra cancelada.", "Compra Cancelada", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Por favor, selecciona una cantidad válida de boletos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una cantidad de boletos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCompraBoletosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Cartelera c=new Cartelera(sucursal,this.c);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CompraBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CompraBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CompraBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CompraBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CompraBoleto().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompraBoletos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Integer> comboBoxCantidadBoletos;
    private javax.swing.JPanel informacionDeFuncion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
