/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;

/**
 *
 * @author rramirez
 */
public class DetalleCompra extends javax.swing.JFrame {

    /**
     * Creates new form DetalleCompra
     */
    public DetalleCompra() {
        initComponents();
        this.cargarMetodosIniciales();
    }

    public void cargarMetodosIniciales() {
        this.cargarConfiguracionInicialPantalla();
    }

    public void cargarConfiguracionInicialPantalla() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblPeliculaImg = new javax.swing.JLabel();
        LblSucursal = new javax.swing.JLabel();
        LblPelicula = new javax.swing.JLabel();
        LblFechaTitulo = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        LblSalaTitulo = new javax.swing.JLabel();
        LblSala = new javax.swing.JLabel();
        LblBoletosTitulo = new javax.swing.JLabel();
        LblBoletos = new javax.swing.JLabel();
        LblCostoTitulo = new javax.swing.JLabel();
        LblCostoTotal = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LblPeliculaImg.setText("(Inserta imagen)");

        LblSucursal.setBackground(new java.awt.Color(255, 255, 255));
        LblSucursal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblSucursal.setForeground(new java.awt.Color(51, 0, 204));
        LblSucursal.setText("(Sucursal)");

        LblPelicula.setBackground(new java.awt.Color(255, 255, 255));
        LblPelicula.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblPelicula.setForeground(new java.awt.Color(51, 0, 204));
        LblPelicula.setText("(Pelicula)");

        LblFechaTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LblFechaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblFechaTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LblFechaTitulo.setText("Fecha");

        LblFecha.setBackground(new java.awt.Color(255, 255, 255));
        LblFecha.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        LblFecha.setForeground(new java.awt.Color(51, 0, 204));
        LblFecha.setText("(Fecha)");

        LblSalaTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LblSalaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblSalaTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LblSalaTitulo.setText("Sala");

        LblSala.setBackground(new java.awt.Color(255, 255, 255));
        LblSala.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        LblSala.setForeground(new java.awt.Color(51, 0, 204));
        LblSala.setText("(Sala)");

        LblBoletosTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LblBoletosTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblBoletosTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LblBoletosTitulo.setText("Boletos");

        LblBoletos.setBackground(new java.awt.Color(255, 255, 255));
        LblBoletos.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        LblBoletos.setForeground(new java.awt.Color(51, 0, 204));
        LblBoletos.setText("(#)");

        LblCostoTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LblCostoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblCostoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LblCostoTitulo.setText("Costo total");

        LblCostoTotal.setBackground(new java.awt.Color(255, 255, 255));
        LblCostoTotal.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        LblCostoTotal.setForeground(new java.awt.Color(51, 0, 204));
        LblCostoTotal.setText("($)");

        BtnAceptar.setText("Aceptar");
        BtnAceptar.setBackground(new java.awt.Color(0, 153, 255));
        BtnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnAtras.setBackground(new java.awt.Color(255, 255, 255));
        BtnAtras.setIcon(new javax.swing.ImageIcon("C:\\Users\\rramirez\\OneDrive\\Escritorio\\BDA_3\\Proyecto01BDA_CINEPOLIS\\Resources\\BtnAtras.png")); // NOI18N
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(LblPeliculaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblSucursal)
                                    .addComponent(LblPelicula)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblFechaTitulo)
                                            .addComponent(LblFecha)
                                            .addComponent(LblSalaTitulo)
                                            .addComponent(LblSala)
                                            .addComponent(LblBoletosTitulo)
                                            .addComponent(LblBoletos))
                                        .addGap(165, 165, 165)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblCostoTitulo)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(LblCostoTotal))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAtras)))
                .addContainerGap(750, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblPeliculaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAtras)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblPelicula)
                        .addGap(29, 29, 29)
                        .addComponent(LblSucursal)
                        .addGap(29, 29, 29)
                        .addComponent(LblFechaTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblFecha)
                        .addGap(18, 18, 18)
                        .addComponent(LblSalaTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblSala)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblBoletosTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblBoletos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblCostoTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblCostoTotal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCancelar)
                        .addGap(151, 151, 151))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rramirez\\OneDrive\\Escritorio\\BDA_3\\Proyecto01BDA_CINEPOLIS\\Resources\\cinepolis_logoMed.png")); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Detalle Compra");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(658, 658, 658)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
        DlgCompraExitosa ce = new DlgCompraExitosa();
        ce.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
//        SucursalesCartelera sc = new SucursalesCartelera();
//        sc.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
       CompraBoletos cp = new CompraBoletos();
       cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel LblBoletos;
    private javax.swing.JLabel LblBoletosTitulo;
    private javax.swing.JLabel LblCostoTitulo;
    private javax.swing.JLabel LblCostoTotal;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblFechaTitulo;
    private javax.swing.JLabel LblPelicula;
    private javax.swing.JLabel LblPeliculaImg;
    private javax.swing.JLabel LblSala;
    private javax.swing.JLabel LblSalaTitulo;
    private javax.swing.JLabel LblSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
