/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;

/**
 *
 * @author rramirez
 */
public class PeliculaResumen extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public PeliculaResumen() {
        initComponents();
        this.cargarMetodosIniciales();
    }

    public void cargarMetodosIniciales() {
        this.cargarConfiguracionInicialPantalla();
    }

    public void cargarConfiguracionInicialPantalla() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LblPelicula = new javax.swing.JLabel();
        LblNombrePelicula = new javax.swing.JLabel();
        BtnComprarBoletos = new javax.swing.JButton();
        LblDuracionMin = new javax.swing.JLabel();
        LblSinopsis = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblImagenPelicula = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtASinopsis = new javax.swing.JTextArea();
        LblTrailer = new javax.swing.JLabel();
        LblClasificacion = new javax.swing.JLabel();
        LblPaisOrigen = new javax.swing.JLabel();
        LblGenero = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnAtras = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        MenuCartelera = new javax.swing.JMenuItem();
        MenuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        LblPelicula.setBackground(new java.awt.Color(0, 0, 0));
        LblPelicula.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LblPelicula.setForeground(new java.awt.Color(0, 0, 0));
        LblPelicula.setText("Película");

        LblNombrePelicula.setBackground(new java.awt.Color(0, 0, 0));
        LblNombrePelicula.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LblNombrePelicula.setForeground(new java.awt.Color(0, 0, 0));
        LblNombrePelicula.setText("(Pelicula)");

        BtnComprarBoletos.setBackground(new java.awt.Color(0, 0, 153));
        BtnComprarBoletos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtnComprarBoletos.setForeground(new java.awt.Color(255, 255, 255));
        BtnComprarBoletos.setText("Comprar boletos");
        BtnComprarBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarBoletosActionPerformed(evt);
            }
        });

        LblDuracionMin.setBackground(new java.awt.Color(0, 0, 0));
        LblDuracionMin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblDuracionMin.setForeground(new java.awt.Color(0, 0, 0));
        LblDuracionMin.setText("Duración: ");

        LblSinopsis.setBackground(new java.awt.Color(0, 0, 0));
        LblSinopsis.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LblSinopsis.setForeground(new java.awt.Color(0, 0, 0));
        LblSinopsis.setText("Sinopsis");

        LblImagenPelicula.setBackground(new java.awt.Color(255, 255, 255));
        LblImagenPelicula.setForeground(new java.awt.Color(0, 0, 0));

        TxtASinopsis.setBackground(new java.awt.Color(255, 255, 255));
        TxtASinopsis.setColumns(20);
        TxtASinopsis.setForeground(new java.awt.Color(0, 0, 0));
        TxtASinopsis.setRows(5);
        jScrollPane1.setViewportView(TxtASinopsis);

        LblTrailer.setBackground(new java.awt.Color(0, 0, 0));
        LblTrailer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblTrailer.setForeground(new java.awt.Color(0, 0, 0));
        LblTrailer.setText("Trailer: ");

        LblClasificacion.setBackground(new java.awt.Color(0, 0, 0));
        LblClasificacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblClasificacion.setForeground(new java.awt.Color(0, 0, 0));
        LblClasificacion.setText("Clasificación: ");

        LblPaisOrigen.setBackground(new java.awt.Color(0, 0, 0));
        LblPaisOrigen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblPaisOrigen.setForeground(new java.awt.Color(0, 0, 0));
        LblPaisOrigen.setText("Pais de origen: ");

        LblGenero.setBackground(new java.awt.Color(0, 0, 0));
        LblGenero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblGenero.setForeground(new java.awt.Color(0, 0, 0));
        LblGenero.setText("Genero: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblPelicula)
                .addGap(642, 642, 642))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LblClasificacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblDuracionMin)
                            .addComponent(LblNombrePelicula)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LblImagenPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblSinopsis)
                                    .addComponent(LblTrailer)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblGenero)
                            .addComponent(LblPaisOrigen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnComprarBoletos)
                        .addGap(448, 448, 448))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LblPelicula)
                .addGap(94, 94, 94)
                .addComponent(LblNombrePelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblDuracionMin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(LblSinopsis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LblTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(LblImagenPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(LblClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LblPaisOrigen))
                    .addComponent(BtnComprarBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Panel.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rramirez\\OneDrive\\Escritorio\\BDA_3\\Proyecto01BDA_CINEPOLIS\\Resources\\cinepolis_logo.png")); // NOI18N

        BtnAtras.setBackground(new java.awt.Color(0, 0, 153));
        BtnAtras.setForeground(new java.awt.Color(0, 0, 153));
        BtnAtras.setIcon(new javax.swing.ImageIcon("C:\\Users\\rramirez\\OneDrive\\Escritorio\\BDA_3\\Proyecto01BDA_CINEPOLIS\\Resources\\BtnAtras.png")); // NOI18N
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(BtnAtras)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(369, 369, 369)
                .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        MenuOpciones.setText("Opciones");

        MenuCartelera.setText("Cartelera");
        MenuCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCarteleraActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuCartelera);

        MenuCerrarSesion.setText("Cerrar Sesión");
        MenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCerrarSesionActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuCerrarSesion);

        jMenuBar1.add(MenuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnComprarBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarBoletosActionPerformed
        // TODO add your handling code here:
        CompraBoletos cb = new CompraBoletos();
        cb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnComprarBoletosActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
        SucursalesCartelera sc = new SucursalesCartelera();
        sc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void MenuCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCarteleraActionPerformed
        // TODO add your handling code here:
        SucursalesCartelera sc = new SucursalesCartelera();
        sc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuCarteleraActionPerformed

    private void MenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCerrarSesionActionPerformed
        // TODO add your handling code here:
        InicioSesion i = new InicioSesion();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnComprarBoletos;
    private javax.swing.JLabel LblClasificacion;
    private javax.swing.JLabel LblDuracionMin;
    private javax.swing.JLabel LblGenero;
    private javax.swing.JLabel LblImagenPelicula;
    private javax.swing.JLabel LblNombrePelicula;
    private javax.swing.JLabel LblPaisOrigen;
    private javax.swing.JLabel LblPelicula;
    private javax.swing.JLabel LblSinopsis;
    private javax.swing.JLabel LblTrailer;
    private javax.swing.JMenuItem MenuCartelera;
    private javax.swing.JMenuItem MenuCerrarSesion;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextArea TxtASinopsis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
