/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Negocio.DTOs.ClienteDTO;
import Negocio.Negocio.ClienteNegocio;
import excepciones.cinepolisException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rramirez
 */
public class Registro extends javax.swing.JFrame {

    ClienteNegocio negocio;
    
    /**
     * Creates new form InicioSesion
     */
    public Registro() {
        initComponents();
        this.cargarMetodosIniciales();
        this.setLocationRelativeTo(this);
        this.setSize(780, 560);
    }

    public void cargarMetodosIniciales() {
        this.cargarConfiguracionInicialPantalla();
    }

    public void cargarConfiguracionInicialPantalla() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnRegistrarse = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtContrasena1 = new javax.swing.JPasswordField();
        textoCoordenadas = new javax.swing.JTextField();
        lblContraseña1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre completo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 180, 20));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 270, 30));

        lblCorreo.setFont(new java.awt.Font("Shree Devanagari 714", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 270, 30));

        lblContraseña.setFont(new java.awt.Font("Shree Devanagari 714", 0, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Ubicacion: (coordenadas)");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Shree Devanagari 714", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de nacimiento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 270, 30));

        btnRegistrarse.setBackground(new java.awt.Color(51, 204, 255));
        btnRegistrarse.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 270, 30));
        jPanel1.add(txtContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 270, 30));

        textoCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCoordenadasActionPerformed(evt);
            }
        });
        jPanel1.add(textoCoordenadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 270, 30));

        lblContraseña1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 18)); // NOI18N
        lblContraseña1.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña1.setText("Contraseña:");
        jPanel1.add(lblContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
        try {
            ClienteDTO clienteDTO = new ClienteDTO();

            String[] nombreC = txtNombre.getText().split(" ");
            int cantidad = nombreC.length;

            if (cantidad < 3) {
                new cinepolisException("Nombre inválido");
            }

            if (cantidad > 3) {
                clienteDTO.setApellidoMaterno(nombreC[nombreC.length - 1]);
                clienteDTO.setApellidoPaterno(nombreC[nombreC.length - 2]);
                String nombreAuxiliar = "";
                for (int i = 0; i < nombreC.length - 2; i++) {
                    nombreAuxiliar += nombreC[i] + " ";
                }
                clienteDTO.setNombre(nombreAuxiliar);
            }else{
                clienteDTO.setNombre(nombreC[0]);
                clienteDTO.setApellidoPaterno(nombreC[1]);
                clienteDTO.setApellidoMaterno(nombreC[2]);
            }

            clienteDTO.setCorreo(txtCorreo.getText());
            clienteDTO.setContrasena(txtContrasena.getText());
            clienteDTO.setFechaNacimiento(jDateChooser1.getDate());
            clienteDTO.setUbicacion(textoCoordenadas.getText());

            //
            if (negocio.registro(clienteDTO) != null) {
                InicioSesion inicioSesion = new InicioSesion(negocio);
                inicioSesion.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo registrar el usuario");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void textoCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCoordenadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCoordenadasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblContraseña1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JTextField textoCoordenadas;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JPasswordField txtContrasena1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
