/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;

/**
 *
 * @author rramirez
 */
public class SucursalesCartelera extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public SucursalesCartelera() {
        initComponents();
        this.cargarMetodosIniciales();
    }

    public void cargarMetodosIniciales() {
        this.cargarConfiguracionInicialPantalla();
    }

    public void cargarConfiguracionInicialPantalla() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LblSucursales = new javax.swing.JLabel();
        LblCiudad = new javax.swing.JLabel();
        BtnBuscarSucursal = new javax.swing.JButton();
        CmbxCiudad = new javax.swing.JComboBox<>();
        CmbxSucursal = new javax.swing.JComboBox<>();
        LblCiudad1 = new javax.swing.JLabel();
        LblPagina = new javax.swing.JLabel();
        LblCiudad2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCartelera = new javax.swing.JTable();
        LblCartelera = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnAtrasTabla = new javax.swing.JButton();
        BtnAdelanteTabla = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnAtras = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        MenuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        LblSucursales.setBackground(new java.awt.Color(0, 0, 0));
        LblSucursales.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LblSucursales.setForeground(new java.awt.Color(0, 0, 0));
        LblSucursales.setText("Sucursales");

        LblCiudad.setBackground(new java.awt.Color(0, 0, 0));
        LblCiudad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LblCiudad.setForeground(new java.awt.Color(0, 0, 0));
        LblCiudad.setText("Ciudad");

        BtnBuscarSucursal.setBackground(new java.awt.Color(0, 204, 255));
        BtnBuscarSucursal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnBuscarSucursal.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarSucursal.setText("Buscar sucursal mas cercana");
        BtnBuscarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarSucursalActionPerformed(evt);
            }
        });

        CmbxCiudad.setBackground(new java.awt.Color(255, 255, 255));
        CmbxCiudad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CmbxCiudad.setForeground(new java.awt.Color(0, 0, 0));

        CmbxSucursal.setBackground(new java.awt.Color(255, 255, 255));
        CmbxSucursal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CmbxSucursal.setForeground(new java.awt.Color(0, 0, 0));

        LblCiudad1.setBackground(new java.awt.Color(0, 0, 0));
        LblCiudad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblCiudad1.setForeground(new java.awt.Color(0, 0, 0));
        LblCiudad1.setText("Seleccionar");

        LblPagina.setBackground(new java.awt.Color(0, 0, 0));
        LblPagina.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LblPagina.setForeground(new java.awt.Color(0, 0, 0));
        LblPagina.setText("1");

        LblCiudad2.setBackground(new java.awt.Color(0, 0, 0));
        LblCiudad2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LblCiudad2.setForeground(new java.awt.Color(0, 0, 0));
        LblCiudad2.setText("Sucursal");

        TblCartelera.setBackground(new java.awt.Color(255, 255, 255));
        TblCartelera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TblCartelera.setForeground(new java.awt.Color(0, 0, 0));
        TblCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "(Nombre 1)", "(Nombre 2)", "(Nombre 3)"
            }
        ));
        jScrollPane1.setViewportView(TblCartelera);

        LblCartelera.setBackground(new java.awt.Color(0, 0, 0));
        LblCartelera.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LblCartelera.setForeground(new java.awt.Color(0, 0, 0));
        LblCartelera.setText("Cartelera");

        BtnAtrasTabla.setBackground(new java.awt.Color(255, 255, 255));
        BtnAtrasTabla.setIcon(new javax.swing.ImageIcon("C:\\Users\\rramirez\\OneDrive\\Escritorio\\BDA_3\\Proyecto01BDA_CINEPOLIS\\Resources\\BtnAtrasT.png")); // NOI18N

        BtnAdelanteTabla.setBackground(new java.awt.Color(255, 255, 255));
        BtnAdelanteTabla.setIcon(new javax.swing.ImageIcon("C:\\Users\\rramirez\\OneDrive\\Escritorio\\BDA_3\\Proyecto01BDA_CINEPOLIS\\Resources\\BtnAdelanteT.png")); // NOI18N
        BtnAdelanteTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdelanteTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAtrasTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblCiudad))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LblCiudad2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CmbxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                                .addComponent(BtnBuscarSucursal)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAdelanteTabla)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LblCiudad1)
                        .addGap(687, 687, 687))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LblCartelera)
                        .addGap(623, 623, 623))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LblPagina)
                        .addGap(682, 682, 682))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LblSucursales)
                        .addGap(611, 611, 611))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LblSucursales)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCiudad)
                    .addComponent(LblCiudad2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CmbxCiudad)
                            .addComponent(CmbxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(LblCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscarSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAtrasTabla)
                        .addGap(263, 263, 263))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(BtnAdelanteTabla)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(LblPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );

        Panel.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rramirez\\OneDrive\\Escritorio\\BDA_3\\Proyecto01BDA_CINEPOLIS\\Resources\\cinepolis_logo.png")); // NOI18N

        BtnAtras.setBackground(new java.awt.Color(0, 0, 153));
        BtnAtras.setForeground(new java.awt.Color(0, 0, 153));
        BtnAtras.setIcon(new javax.swing.ImageIcon("C:\\Users\\rramirez\\OneDrive\\Escritorio\\BDA_3\\Proyecto01BDA_CINEPOLIS\\Resources\\BtnAtras.png")); // NOI18N
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(BtnAtras))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(262, 262, 262)
                .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        MenuOpciones.setText("Opciones");

        MenuCerrarSesion.setText("Cerrar Sesión");
        MenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCerrarSesionActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuCerrarSesion);

        jMenuBar1.add(MenuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarSucursalActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
        InicioSesion i = new InicioSesion();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnAdelanteTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdelanteTablaActionPerformed
        // TODO add your handling code here:
        PeliculaResumen pl = new PeliculaResumen();
        pl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAdelanteTablaActionPerformed

    private void MenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCerrarSesionActionPerformed
        // TODO add your handling code here:
        InicioSesion i = new InicioSesion();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdelanteTabla;
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnAtrasTabla;
    private javax.swing.JButton BtnBuscarSucursal;
    private javax.swing.JComboBox<String> CmbxCiudad;
    private javax.swing.JComboBox<String> CmbxSucursal;
    private javax.swing.JLabel LblCartelera;
    private javax.swing.JLabel LblCiudad;
    private javax.swing.JLabel LblCiudad1;
    private javax.swing.JLabel LblCiudad2;
    private javax.swing.JLabel LblPagina;
    private javax.swing.JLabel LblSucursales;
    private javax.swing.JMenuItem MenuCerrarSesion;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JPanel Panel;
    private javax.swing.JTable TblCartelera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
